name: Comment
on: pull_request
jobs:
  comment:
    runs-on: ubuntu-latest
    permissions:            # GITHUB_TOKEN permissions
      pull-requests: write  # Required to comment on PRs
      contents: read        # Required to read the PR contents
    steps:
      - uses: actions/checkout@v4
      - run: gh pr comment "${GITHUB_HEAD_REF}" --body "Hello, ${GITHUB_ACTOR}" # Comment on the PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Use the GITHUB_TOKEN secret to authenticate