name: functions
on: push
jobs:
  compare:
    runs-on: ubuntu-latest
    steps:
      - run: printenv | grep '_FUNC'
        env:
          CONTAINS_FUNC: ${{ contains('Hello', 'ello') }}     # Check if 'Hello' contains 'ello'
          STARTS_WITH_FUNC: ${{ startsWith('Hello', 'He') }}  # Check if 'Hello' starts with 'He'
          ENDS_WITH_FUNC: ${{ endsWith('Hello', 'lo') }}      # Check if 'Hello' ends with 'lo'
