name: Generate functions
on: push
jobs:
  compare:
    runs-on: ubuntu-latest
    steps:
      - run: printenv | grep '_FUNC'
        env:
          FORMAT_FUNC: ${{ format('{0} {1}', 'Hi', 'World') }}  # Format a string with placeholders
          JOIN_FUNC: ${{ join(github.event.*.html_url, ', ') }} # Join an array into a string with a separator
