name: JSON functions
on: push
jobs:
  compare:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${CONTEXT}"
        env:
          CONTEXT: ${{ toJson(github) }}  # Convert the github context to JSON
