name: Reusable Workflows
on:
    workflow_call:
        inputs:
            pr-number:
                type: string
                default: ${{ github.event.pull_request.number }}
                required: true
                description: 'プルリクエスト番号'
        secrets:
            token:
                description: 'GitHub Token'
                required: true
        options:
            messge:
                value: ${{ jobs.comment.outputs.pr-comment }}
                description: 'コメントメッセージ'
jobs:
    comment:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            pull-requests: write
        steps:
            - uses: actions/checkout@v4
            - id: pr-comment
              run: |
                body="Welcome, ${GITHUB_ACTOR}"
                gh pr comment "${PR_NUMBER}" --body "${body}"
                echo "body=${body}" >> "${GITHUB_OUTPUT}"
              env:
                GITHUB_TOKEN: ${{ secrets.token }}
                PR_NUMBER: ${{ inputs.pr-number }}
        outputs:
            pr-comment: ${{ steps.pr-comment.outputs.body }}